acme_service:
    type: rest
    prefix: /api
    resource: "@AcmeBlogBundle/Resources/config/routes.yml"

acme_blog:
    resource: "@AcmeBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
