imports:
    - { resource: '@DBServiceBundle/Resources/config/security.yml' }

security:
    encoders:
      'FOS\UserBundle\Model\UserInterface': sha512

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/service/.*, role: ROLE_USER }
