<?php

namespace DB\porteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * accountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accountRepository extends EntityRepository
{
}
