<?php

namespace DB\porteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Account_historicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Account_historicRepository extends EntityRepository
{
}
