DB_Service_Organisation:
    type: rest
    resource: "DB\ServiceBundle\Controller\OrganisationController"
DB_Service_Website:
    type: rest
    resource: "DB\ServiceBundle\Controller\WebsiteController"
DB_Service_Account:
    type: rest
    resource: "DB\ServiceBundle\Controller\AccountController"
DB_Service_AccountHistoric:
    type: rest
    resource: "DB\ServiceBundle\Controller\AccountHistoricController"