d_bporte_homepage:
    path:     /
    defaults: { _controller: DBporteBundle:Advert:index }

d_bporte_view:
    path:     /advert/{id}
    defaults: { _controller: DBporteBundle:Advert:view }

d_bporte_view_DBase:
    path:     /dbase/{mail}
    defaults: { _controller: DBporteBundle:DBase:view }

d_bporte_view_slug:
    path:     /{year}/{slug}.{_format}
    defaults: { _controller: DBporteBundle:Advert:viewSlug, format: html }
    requirements:
        year:   \d{4}
        format: html|xml

d_bporte_add:
    path:     /add
    defaults: { _controller: DBporteBundle:Advert:add }
